server:
  port: 50201
  servlet:
    context-path: /api
spring:
  application:
    name: xc-govern-gateway
  redis:
    host: ${REDIS_HOST:127.0.0.1}
    port: ${REDIS_PORT:6379}
    timeout: 5000 #连接超时 毫秒
    database: 1
    jedis:
      pool:
        maxActive: 3
        maxIdle: 3
        minIdle: 1
        maxWait: -1 #连接池最大等行时间 -1没有限制
eureka:
  client:
    service-url:
      defaultZone: http://localhost:50101/eureka/,http://localhost:50102/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    ip-address: 127.0.0.1
ribbon:
  MaxAutoRetries: 2 #最大重试次数，当Eureka中可以找到服务，但是服务连不上时将会重试，如果eureka中找不到服务则直接走断路器
  MaxAutoRetriesNextServer: 3 #切换实例的重试次数
  OkToRetryOnAllOperations: false  #对所有操作请求都进行重试，如果是get则可以，如果是post，put等操作没有实现幂等的情况下是很危险的,所以设置为false
  ConnectTimeout: 5000  #请求连接的超时时间
  ReadTimeout: 6000 #请求处理的超时时间
zuul:
  routes:
    manage-course:
      path: /course/** # 路由配置
      serviceId: xc-service-manage-course # 服务id
      # 配置了这两个之后，请求localhost:50201/api/course之后，就会转发到localhost:31200/course
      # url: http://localhost:31200 #也可指定url
      strip-prefix: false # 代理转发时是否去掉前缀，即把/course去掉，这里不去掉，因为我们的课程服务就是以/course打头的
      sensitiveHeaders: # 不屏蔽cookie
    manage-course-category:
      path: /category/**
      serviceId: xc-service-manage-course
      strip-prefix: false
      sensitiveHeaders:
    manage-course-coursepage:
      path: /coursepage/**
      serviceId: xc-service-manage-course
      strip-prefix: false
      sensitiveHeaders:
    xc-service-learning:
      path: /learning/**
      serviceId: xc-service-learning
      strip-prefix: false
      sensitiveHeaders:
    manage-cms:
      path: /cms/**
      serviceId: xc-service-manage-cms
      strip-prefix: false
      sensitiveHeaders:
    manage-sys:
      path: /sys/**
      serviceId: xc-service-manage-cms
      strip-prefix: false
      sensitiveHeaders:
    service-ucenter:
      path: /ucenter/**
      serviceId: xc-service-ucenter
      sensitiveHeaders:
      strip-prefix: false
    xc-service-manage-order:
      path: /order/**
      serviceId: xc-service-manage-order
      sensitiveHeaders:
      strip-prefix: false